routes/backend.php
<?php
/**
 * Created by PhpStorm.
 * User: bredevil
 * Date: 11.03.2019
 * Time: 12:37
 */

Route::group(['prefix' => 'backend'], function() {

    Route::group(['middleware' => ['guest']], function() {
        Route::get('/', 'Auth\LoginController@loginForm')->name('login');
        Route::post('/', 'Auth\LoginController@login')->name('auth');
    });
    Route::group(['middleware' => ['guest']], function() {
        Route::get('/login', 'Auth\LoginController@loginForm')->name('login');
        Route::post('/', 'Auth\LoginController@login')->name('auth');
    });

    // admin panel
    Route::group(['middleware' => ['auth']], function() {
        Route::get('/dashboard', 'DashboardController@index');
        Route::get('/logout', 'Auth\LoginController@logout');
        // admin panel
        Route::group(['middleware' => ['auth']], function() {
            Route::get('/', 'DashboardController@index');
            Route::get('/dashboard', 'DashboardController@index')
                ->name('dashboard');
            Route::get('/logout', 'Auth\LoginController@logout');

            // pages
            Route::resource('homepage', 'Backend\Page\HomepageController');
            Route::post('opinions/sort/', 'Backend\Page\OpinionController@sort')
                ->name('opinions.sort');
            Route::resource('opinions', 'Backend\Page\OpinionController');
            Route::resource('creatorpage',
                'Backend\Page\CreatorpageController');

            Route::resource('discounts', 'Backend\Discount\DiscountController');

            // seo
            Route::resource('profile', 'Backend\Profile\ProfileController');

            Route::resource('seoscripts', 'Backend\Seo\SeoscriptController');
            Route::resource('redirects', 'Backend\Seo\RedirectController');
            Route::resource('sitemap', 'Backend\Seo\SitemapController');

            // contacts
            Route::resource('phones', 'Backend\Contact\PhoneController');
            Route::resource('sociallinks',
                'Backend\Contact\SociallinkController');
            Route::resource('cities', 'Backend\Contact\CityController');

            Route::resource('tests', 'Backend\Test\TestController');
            Route::resource('ttypes', 'Backend\Test\TtypeController');
            Route::resource('course-tests',
                'Backend\Test\CourseTestController');
            Route::resource('test-content', 'Backend\Test\TestPageController');

            // courses
            Route::group(['middleware' => ['permission:courses']], function() {
                // types
                Route::resource('types', 'Backend\Course\TypeController');
                // actions
                Route::resource('actions', 'Backend\Course\ActionController');
                // courses gallery
                Route::group(['prefix' => 'courses/image'], function() {
                    Route::post('upload/{id}',
                        'Backend\Course\CourseImageController@uploadImage');
                    Route::post('get/{id}',
                        'Backend\Course\CourseImageController@getImages');
                    Route::post('delete',
                        'Backend\Course\CourseImageController@deleteImage');
                    Route::post('get',
                        'Backend\Course\CourseImageController@getImage');
                    Route::post('set',
                        'Backend\Course\CourseImageController@setImage');
                    Route::post('sort',
                        'Backend\Course\CourseImageController@sortImage');
                });

                // courses
                Route::post('courses/sort/',
                    'Backend\Course\CourseController@sort');
                Route::post('courses/disable-action',
                    'Backend\Course\CourseController@disableAction')
                    ->name('courses.disable-action');
                Route::resource('courses', 'Backend\Course\CourseController');

                // events gallery
                Route::group(['prefix' => 'events/image'], function() {
                    Route::post('upload/{id}',
                        'Backend\Event\EventImageController@uploadImage');
                    Route::post('get/{id}',
                        'Backend\Event\EventImageController@getImages');
                    Route::post('delete',
                        'Backend\Event\EventImageController@deleteImage');
                    Route::post('get',
                        'Backend\Event\EventImageController@getImage');
                    Route::post('set',
                        'Backend\Event\EventImageController@setImage');
                    Route::post('sort',
                        'Backend\Event\EventImageController@sortImage');
                });

                // events
                Route::resource('events', 'Backend\Event\EventController');
            });

            // teachers
            Route::group(['middleware' => ['permission:teachers']], function() {
                Route::post('teachers/sort/',
                    'Backend\Teacher\TeacherController@sort');
                Route::resource('teachers',
                    'Backend\Teacher\TeacherController');
            });

            // settings
            Route::group(['middleware' => ['permission:settings']], function() {

                // settings
                Route::get('settings/empty_cache',
                    'SettingsController@setEmptyCache')->name('clear-cache');
                Route::get('settings/optimize-images',
                    'SettingsController@optimizeImages')
                    ->name('optimize-images');
                Route::resource('settings', 'SettingsController');

                // configs (telegram)
                Route::resource('telegram-configs',
                    'Backend\Config\TelegramconfigController');

                // users
                Route::resource('users', 'UsersController');

                // permissions
                Route::resource('permissions', 'PermissionsController');
                Route::post('permissions/remove/',
                    'PermissionsController@remove');

                // roles
                Route::resource('roles', 'RolesController');
                Route::post('roles/remove/', 'RolesController@remove');

                // creators
                Route::post('creators/sort/',
                    'Backend\Creator\CreatorController@sort');
                Route::resource('creators',
                    'Backend\Creator\CreatorController');
            });

            // students
            Route::group(['middleware' => ['permission:students']], function() {
                Route::resource('students',
                    'Backend\Student\StudentController');
            });

            // partners
            Route::group(['middleware' => ['permission:partners']], function() {
                Route::post('partners/sort/',
                    'Backend\Partner\PartnerController@sort');
                Route::resource('partners',
                    'Backend\Partner\PartnerController');
            });

            // applications
            Route::group(['middleware' => ['permission:applications']],
                function() {
                    // reviews
                    Route::resource('reviews',
                        'Backend\Review\ReviewController');

                    // applications(students)

                    Route::get('stapplications/export/',
                        'Backend\Application\StapplicationController@export')
                        ->name('stapplications.export');
                    Route::get('stapplications/update-all/',
                        'Backend\Application\StapplicationController@updateAll')
                        ->name('stapplications.update-all');
                    Route::resource('stapplications',
                        'Backend\Application\StapplicationController');

                    // applications(teachers)
                    Route::get('teachapplications/export/',
                        'Backend\Application\TeachapplicationController@export')
                        ->name('teachapplications.export');
                    Route::get('teachapplications/update-all/',
                        'Backend\Application\TeachapplicationController@updateAll')
                        ->name('teachapplications.update-all');
                    Route::resource('teachapplications',
                        'Backend\Application\TeachapplicationController');

                    // applications(callback)
                    Route::get('callbackapplications/update-all/',
                        'Backend\Application\CallbackapplicationController@updateAll')
                        ->name('callbackapplications.update-all');
                    Route::resource('callbackapplications',
                        'Backend\Application\CallbackapplicationController');

                    // applications(partners)
                    Route::get('partnerapplications/update-all/',
                        'Backend\Application\PartnerapplicationController@updateAll')
                        ->name('partnerapplications.update-all');
                    Route::resource('partnerapplications',
                        'Backend\Application\PartnerapplicationController');

                    // applications(events)
                    Route::get('eventapplications/export/',
                        'Backend\Application\EventapplicationController@export')
                        ->name('eventapplications.export');
                    Route::get('eventapplications/update-all/',
                        'Backend\Application\EventapplicationController@updateAll')
                        ->name('eventapplications.update-all');
                    Route::resource('eventapplications',

routes/frontend.php
<?php
/**
 * Created by PhpStorm.
 * User: bredevil
 * Date: 11.03.2019
 * Time: 12:37
 */

Route::post('project_register/',
    'Frontend\ProjectLife\ProjectLifeController@register')
    ->name('project_register');

Route::get('/', 'Frontend\Home\HomeController@index')->name('home');
Route::post('teachers', 'Frontend\Home\HomeController@getTeachers')
    ->name('get-teachers');
Route::post('partners', 'Frontend\Home\HomeController@getPartners')
    ->name('get-partners');
Route::post('events', 'Frontend\Home\HomeController@getEvents')
    ->name('get-events');
Route::post('cities', 'Frontend\Home\HomeController@updateCity')
    ->name('update-city');

// life project 3.0
Route::get('/project-life', 'Frontend\ProjectLife\ProjectLifeController@index')
    ->name('project_home');


// course
Route::get('/course/{course_alias}', 'Frontend\Course\CourseController@index')
    ->name('course');

// tests
Route::group(['prefix' => 'tests', 'as' => 'tests.'], function() {
    Route::get('/result/', 'Frontend\Test\TestController@result')
        ->name('result');
    Route::any('/{id?}', 'Frontend\Test\TestController@index')
        ->name('question');
    Route::any('/check/{id?}', 'Frontend\Test\TestController@check')
        ->name('check');
});

// blog
Route::group(['prefix' => 'blog', 'as' => 'blog.'], function() {
    Route::get('/', 'Frontend\Blog\BlogController@index')
        ->name('blog');
    Route::get('/article/{alias}', 'Frontend\Blog\BlogController@inner')
        ->name('article');
    Route::post('/article/likes', 'Frontend\Blog\BlogController@likes')
        ->name('likes');
    Route::post('/subscribe', 'Frontend\Blog\BlogController@subscribe')
        ->name('subscribe');
    Route::post('/offer-article', 'Frontend\Blog\BlogController@offerArticle')
        ->name('offer-article');
});

// team
Route::get('team', 'Frontend\Creatorpage\CreatorpageController@index')
    ->name('team');
Route::post('get-team', 'Frontend\Creatorpage\CreatorpageController@getTeam')
    ->name('get-team');


//Хаб
Route::get('hub', 'Frontend\Hub\HubController@index')->name('hub');
Route::post('send_message', 'Frontend\Hub\HubController@message')
    ->name('send_message');

//
Route::get('hub', 'Frontend\Hub\HubController@index')->name('hub');

// event
Route::get('/event/{event_alias}', 'Frontend\Event\EventController@index')
    ->name('event');

// any page
Route::get('/{alias?}', 'Frontend\Redirect\RedirectController@index')
    ->where('alias', '([A-Za-z0-9\-_:/]+)')->name('page');

// forms
Route::post('add-feedback', 'Frontend\Form\FormController@addFeedback')
    ->name('add-feedback');
Route::post('add-partner', 'Frontend\Form\FormController@addPartner')
    ->name('add-partner');
Route::post('add-teacher', 'Frontend\Form\FormController@addTeacher')
    ->name('add-teacher');
Route::post('add-review', 'Frontend\Form\FormController@addReview')
    ->name('add-review');
Route::post('add-callback', 'Frontend\Form\FormController@addCallback')
    ->name('add-callback');
Route::post('add-event-application',
    'Frontend\Form\FormController@addEventApplication')
    ->name('add-event-application');

routes/web.php
<?php

    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    /**
     * frontend
     */
    Route::group(['middleware' => 'web'], function () {

        // admin panel
        include 'backend.php';
        // frontend
        include 'frontend.php';
    });

app/Models/Redirect/Redirect.php
<?php

namespace App\Models\Redirect;

use Illuminate\Database\Eloquent\Model;

class Redirect extends Model
{
    protected $fillable = ['source', 'target'];
}

app/Models/Seo/Seoscript.php
<?php

namespace App\Models\Seo;

use Illuminate\Database\Eloquent\Model;

class Seoscript extends Model
{
    protected $guarded = ['id'];
}

app/Http/Controllers/Backend/Seo/RedirectController.php
<?php

namespace App\Http\Controllers\Backend\Seo;

use App\Http\Requests\Seo\RedirectRequest;
use App\Models\Redirect\Redirect;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RedirectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.seo.redirects.index', [
            'data' => Redirect::latest()->paginate(30),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.seo.redirects.create', []);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RedirectRequest $request)
    {
        Redirect::create($request->all());
        return redirect(route('redirects.index'))
            ->with('success', 'Запись успешно создана');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $redirect = Redirect::find($id);
        $redirect->{$request->name} = $request->value;
        return response()->json(['status' => $redirect->update()], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Redirect::find($id)->delete();
        return redirect(route('redirects.index'))
            ->with('success', 'Запись успешно удалена');
    }
}

app/Http/Controllers/Frontend/Redirect/RedirectController.php
<?php

namespace App\Http\Controllers\Frontend\Redirect;

use App\Models\Redirect\Redirect;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RedirectController extends Controller
{
    public function index($url)
    {
        $redirect = Redirect::where('source', '/' . trim($url, '/') . '/')->first();
        if ($redirect) {
            return redirect($redirect->target, 301);
        } else {
            abort(404);
        }
    }
}

resources/views/backend/seo/redirects/create.blade.php
@extends('backend.layouts.app')
@section('pagetitle')
    <div class="page-title">
        <div class="title-env">
            <h1 class="title">Добавление редиректа</h1>
            <p class="description">Добавление нового редиректа</p>
        </div>
        <div class="breadcrumb-env">
            <ol class="breadcrumb bc-1">
                <li>
                    <a href="{{ url('backend/dashboard') }}"><i class="fa-home"></i>Главная</a>
                </li>
                <li>
                    <a href="{{ url('backend/redirects') }}">Редиректы</a>
                </li>
                <li class="active">
                    <strong>Добавление</strong>
                </li>
            </ol>
        </div>
    </div>
@endsection
@section('content')
    {{ Form::open(['url' => route('redirects.store'), 'method' => 'POST', 'class' => 'validate', "novalidate" => 'novalidate', 'files' => true]) }}
    <div class="panel panel-headerless">
        <div class="panel-body">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#main" data-toggle="tab">
                        <span class="visible-xs"><i class="fa-user"></i></span>
                        <span class="hidden-xs">Основная информация</span>
                    </a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="main">

                    <div class="member-form-inputs js_parent_div" data-csrf="{{ csrf_token() }}">
                        <div class="row form-group">
                            <div class="col-sm-3">
                                {{ Form::label('key', 'Источник *', ['class' => 'control-label']) }}
                            </div>
                            <div class="col-sm-9">
                                <div class="input-group">
                                    {{  Form::textarea('source', null, ['class' => 'form-control', 'data-validate' => 'required', 'data-message-required' => 'Поле обязательно для заполнения'])}}
                                </div>
                            </div>
                        </div>
                        <div class="row form-group">
                            <label class="col-sm-3" for="field-1">Цель</label>
                            <div class="col-sm-9">
                                <div class="input-group">
                                    {{  Form::textarea('target', null, ['class' => 'form-control']) }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <div class="form-group">
                <a href="{{ url('backend/redirects') }}" class="btn btn-white"><span class="fa-arrow-left"></span> Назад</a>
                <button type="submit" class="btn btn-success js_form_submit"><span class="fa-save"></span>
                    <b>Сохранить</b>
                </button>
            </div>
        </div>
    </div>
    {{ Form::close() }}

@endsection

resources/views/backend/seo/redirects/index.blade.php
@extends('backend.layouts.app')

@section('pagetitle')
    <div class="page-title">
        <div class="title-env">
            <h1 class="title">Скрипты</h1>
        </div>
        <div class="breadcrumb-env">
            <a href="{{ route('redirects.create') }}" class="btn btn-success"><span class="fa-plus"></span>
                Добавить</a>
        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <div class="tab-content">
                <div class="tab-pane active" id="all">

                    <table class="table table-hover members-table middle-align">
                        <thead>
                        <tr>
                            <th width="10%">id</th>
                            <th width="40%">Источник</th>
                            <th width="40%">Цель</th>
                            <th width="10%">Действие</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($data as $item)
                            <tr class="js-parent-form" data-route="{{ url('backend/redirects/' . $item->id ) }}">
                                <td class="hidden-xs hidden-sm">
                                    <span class="email">{!! $item->id !!}</span>
                                </td>
                                <td class="hidden-xs hidden-sm">
                                    <textarea type="text" name="source" cols="50">{!! $item->source !!}</textarea>
                                </td>
                                <td class="user">
                                    <textarea type="text" name="target"  cols="50">{!! $item->target !!}</textarea>
                                </td>
                                <td class="user">
                                    {!! Form::open(['route' => ['redirects.destroy', $item->id], 'method' => 'delete']) !!}
                                    {!! Form::submit('Удалить', ['class' => 'btn btn-danger js_destroy', 'onclick' => "return confirm('Вы уверены?')"]) !!}
                                    {!! Form::close() !!}
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6"><p class="text-center">По данному запросу результатов не найдено.</p>
                                </td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>

                    <div class="row">
                        <div class="col-sm-6">
                        </div>
                        <div class="col-sm-6 text-right text-center-sm">
                            {{ $data->appends([request()])->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ url('assets/js/inputmask/jquery.inputmask.bundle.js') }}"></script>
@endsection