routes/backend.php
<?php
/**
 * Created by PhpStorm.
 * User: bredevil
 * Date: 11.03.2019
 * Time: 12:37
 */

Route::group(['prefix' => 'backend'], function() {

    Route::group(['middleware' => ['guest']], function() {
        Route::get('/', 'Auth\LoginController@loginForm')->name('login');
        Route::post('/', 'Auth\LoginController@login')->name('auth');
    });
    Route::group(['middleware' => ['guest']], function() {
        Route::get('/login', 'Auth\LoginController@loginForm')->name('login');
        Route::post('/', 'Auth\LoginController@login')->name('auth');
    });

    // admin panel
    Route::group(['middleware' => ['auth']], function() {
        Route::get('/dashboard', 'DashboardController@index');
        Route::get('/logout', 'Auth\LoginController@logout');
        // admin panel
        Route::group(['middleware' => ['auth']], function() {
            Route::get('/', 'DashboardController@index');
            Route::get('/dashboard', 'DashboardController@index')
                ->name('dashboard');
            Route::get('/logout', 'Auth\LoginController@logout');

            // pages
            Route::resource('homepage', 'Backend\Page\HomepageController');
            Route::post('opinions/sort/', 'Backend\Page\OpinionController@sort')
                ->name('opinions.sort');
            Route::resource('opinions', 'Backend\Page\OpinionController');
            Route::resource('creatorpage',
                'Backend\Page\CreatorpageController');

            Route::resource('discounts', 'Backend\Discount\DiscountController');

            // seo
            Route::resource('profile', 'Backend\Profile\ProfileController');

            Route::resource('seoscripts', 'Backend\Seo\SeoscriptController');
            Route::resource('redirects', 'Backend\Seo\RedirectController');
            Route::resource('sitemap', 'Backend\Seo\SitemapController');

            // contacts
            Route::resource('phones', 'Backend\Contact\PhoneController');
            Route::resource('sociallinks',
                'Backend\Contact\SociallinkController');
            Route::resource('cities', 'Backend\Contact\CityController');

            Route::resource('tests', 'Backend\Test\TestController');
            Route::resource('ttypes', 'Backend\Test\TtypeController');
            Route::resource('course-tests',
                'Backend\Test\CourseTestController');
            Route::resource('test-content', 'Backend\Test\TestPageController');

            // courses
            Route::group(['middleware' => ['permission:courses']], function() {
                // types
                Route::resource('types', 'Backend\Course\TypeController');
                // actions
                Route::resource('actions', 'Backend\Course\ActionController');
                // courses gallery
                Route::group(['prefix' => 'courses/image'], function() {
                    Route::post('upload/{id}',
                        'Backend\Course\CourseImageController@uploadImage');
                    Route::post('get/{id}',
                        'Backend\Course\CourseImageController@getImages');
                    Route::post('delete',
                        'Backend\Course\CourseImageController@deleteImage');
                    Route::post('get',
                        'Backend\Course\CourseImageController@getImage');
                    Route::post('set',
                        'Backend\Course\CourseImageController@setImage');
                    Route::post('sort',
                        'Backend\Course\CourseImageController@sortImage');
                });

                // courses
                Route::post('courses/sort/',
                    'Backend\Course\CourseController@sort');
                Route::post('courses/disable-action',
                    'Backend\Course\CourseController@disableAction')
                    ->name('courses.disable-action');
                Route::resource('courses', 'Backend\Course\CourseController');

                // events gallery
                Route::group(['prefix' => 'events/image'], function() {
                    Route::post('upload/{id}',
                        'Backend\Event\EventImageController@uploadImage');
                    Route::post('get/{id}',
                        'Backend\Event\EventImageController@getImages');
                    Route::post('delete',
                        'Backend\Event\EventImageController@deleteImage');
                    Route::post('get',
                        'Backend\Event\EventImageController@getImage');
                    Route::post('set',
                        'Backend\Event\EventImageController@setImage');
                    Route::post('sort',
                        'Backend\Event\EventImageController@sortImage');
                });

                // events
                Route::resource('events', 'Backend\Event\EventController');
            });

            // teachers
            Route::group(['middleware' => ['permission:teachers']], function() {
                Route::post('teachers/sort/',
                    'Backend\Teacher\TeacherController@sort');
                Route::resource('teachers',
                    'Backend\Teacher\TeacherController');
            });

            // settings
            Route::group(['middleware' => ['permission:settings']], function() {

                // settings
                Route::get('settings/empty_cache',
                    'SettingsController@setEmptyCache')->name('clear-cache');
                Route::get('settings/optimize-images',
                    'SettingsController@optimizeImages')
                    ->name('optimize-images');
                Route::resource('settings', 'SettingsController');

                // configs (telegram)
                Route::resource('telegram-configs',
                    'Backend\Config\TelegramconfigController');

                // users
                Route::resource('users', 'UsersController');

                // permissions
                Route::resource('permissions', 'PermissionsController');
                Route::post('permissions/remove/',
                    'PermissionsController@remove');

                // roles
                Route::resource('roles', 'RolesController');
                Route::post('roles/remove/', 'RolesController@remove');

                // creators
                Route::post('creators/sort/',
                    'Backend\Creator\CreatorController@sort');
                Route::resource('creators',
                    'Backend\Creator\CreatorController');
            });

            // students
            Route::group(['middleware' => ['permission:students']], function() {
                Route::resource('students',
                    'Backend\Student\StudentController');
            });

            // partners
            Route::group(['middleware' => ['permission:partners']], function() {
                Route::post('partners/sort/',
                    'Backend\Partner\PartnerController@sort');
                Route::resource('partners',
                    'Backend\Partner\PartnerController');
            });

            // applications
            Route::group(['middleware' => ['permission:applications']],
                function() {
                    // reviews
                    Route::resource('reviews',
                        'Backend\Review\ReviewController');

                    // applications(students)

                    Route::get('stapplications/export/',
                        'Backend\Application\StapplicationController@export')
                        ->name('stapplications.export');
                    Route::get('stapplications/update-all/',
                        'Backend\Application\StapplicationController@updateAll')
                        ->name('stapplications.update-all');
                    Route::resource('stapplications',
                        'Backend\Application\StapplicationController');

                    // applications(teachers)
                    Route::get('teachapplications/export/',
                        'Backend\Application\TeachapplicationController@export')
                        ->name('teachapplications.export');
                    Route::get('teachapplications/update-all/',
                        'Backend\Application\TeachapplicationController@updateAll')
                        ->name('teachapplications.update-all');
                    Route::resource('teachapplications',
                        'Backend\Application\TeachapplicationController');

                    // applications(callback)
                    Route::get('callbackapplications/update-all/',
                        'Backend\Application\CallbackapplicationController@updateAll')
                        ->name('callbackapplications.update-all');
                    Route::resource('callbackapplications',
                        'Backend\Application\CallbackapplicationController');

                    // applications(partners)
                    Route::get('partnerapplications/update-all/',
                        'Backend\Application\PartnerapplicationController@updateAll')
                        ->name('partnerapplications.update-all');
                    Route::resource('partnerapplications',
                        'Backend\Application\PartnerapplicationController');

                    // applications(events)
                    Route::get('eventapplications/export/',
                        'Backend\Application\EventapplicationController@export')
                        ->name('eventapplications.export');
                    Route::get('eventapplications/update-all/',
                        'Backend\Application\EventapplicationController@updateAll')
                        ->name('eventapplications.update-all');
                    Route::resource('eventapplications',

routes/frontend.php
<?php
/**
 * Created by PhpStorm.
 * User: bredevil
 * Date: 11.03.2019
 * Time: 12:37
 */

Route::post('project_register/',
    'Frontend\ProjectLife\ProjectLifeController@register')
    ->name('project_register');

Route::get('/', 'Frontend\Home\HomeController@index')->name('home');
Route::post('teachers', 'Frontend\Home\HomeController@getTeachers')
    ->name('get-teachers');
Route::post('partners', 'Frontend\Home\HomeController@getPartners')
    ->name('get-partners');
Route::post('events', 'Frontend\Home\HomeController@getEvents')
    ->name('get-events');
Route::post('cities', 'Frontend\Home\HomeController@updateCity')
    ->name('update-city');

// life project 3.0
Route::get('/project-life', 'Frontend\ProjectLife\ProjectLifeController@index')
    ->name('project_home');


// course
Route::get('/course/{course_alias}', 'Frontend\Course\CourseController@index')
    ->name('course');

// tests
Route::group(['prefix' => 'tests', 'as' => 'tests.'], function() {
    Route::get('/result/', 'Frontend\Test\TestController@result')
        ->name('result');
    Route::any('/{id?}', 'Frontend\Test\TestController@index')
        ->name('question');
    Route::any('/check/{id?}', 'Frontend\Test\TestController@check')
        ->name('check');
});

// blog
Route::group(['prefix' => 'blog', 'as' => 'blog.'], function() {
    Route::get('/', 'Frontend\Blog\BlogController@index')
        ->name('blog');
    Route::get('/article/{alias}', 'Frontend\Blog\BlogController@inner')
        ->name('article');
    Route::post('/article/likes', 'Frontend\Blog\BlogController@likes')
        ->name('likes');
    Route::post('/subscribe', 'Frontend\Blog\BlogController@subscribe')
        ->name('subscribe');
    Route::post('/offer-article', 'Frontend\Blog\BlogController@offerArticle')
        ->name('offer-article');
});

// team
Route::get('team', 'Frontend\Creatorpage\CreatorpageController@index')
    ->name('team');
Route::post('get-team', 'Frontend\Creatorpage\CreatorpageController@getTeam')
    ->name('get-team');


//Хаб
Route::get('hub', 'Frontend\Hub\HubController@index')->name('hub');
Route::post('send_message', 'Frontend\Hub\HubController@message')
    ->name('send_message');

//
Route::get('hub', 'Frontend\Hub\HubController@index')->name('hub');

// event
Route::get('/event/{event_alias}', 'Frontend\Event\EventController@index')
    ->name('event');

// any page
Route::get('/{alias?}', 'Frontend\Redirect\RedirectController@index')
    ->where('alias', '([A-Za-z0-9\-_:/]+)')->name('page');

// forms
Route::post('add-feedback', 'Frontend\Form\FormController@addFeedback')
    ->name('add-feedback');
Route::post('add-partner', 'Frontend\Form\FormController@addPartner')
    ->name('add-partner');
Route::post('add-teacher', 'Frontend\Form\FormController@addTeacher')
    ->name('add-teacher');
Route::post('add-review', 'Frontend\Form\FormController@addReview')
    ->name('add-review');
Route::post('add-callback', 'Frontend\Form\FormController@addCallback')
    ->name('add-callback');
Route::post('add-event-application',
    'Frontend\Form\FormController@addEventApplication')
    ->name('add-event-application');

routes/web.php
<?php

    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    /**
     * frontend
     */
    Route::group(['middleware' => 'web'], function () {

        // admin panel
        include 'backend.php';
        // frontend
        include 'frontend.php';
    });

app/Http/Controllers/Backend/Application/CallbackapplicationController.php
<?php

namespace App\Http\Controllers\Backend\Application;

use App\Models\Application\Callbackapplication;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CallbackapplicationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view('backend.callbackapplications.index', [
            'applications' => Callbackapplication::latest()->paginate(10),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $application = Callbackapplication::find($id);
        $application->viewed = true;
        $application->update();
        return view('backend.callbackapplications.show', [
            'application' => $application,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * @return \Illuminate\Http\RedirectResponse
     */
    public function updateAll()
    {
        Callbackapplication::where('viewed', 0)->update(['viewed' => 1]);
        return redirect('backend/callbackapplications/')
            ->with('success', 'Записи успешно обновлены');
    }
}

app/Http/Controllers/Backend/Blog/SubscriberController.php
<?php

namespace App\Http\Controllers\Backend\Blog;

use App\Exports\SubscribersExport;
use App\Models\Blog\Subscriber;
use App\Http\Controllers\Controller;
use Illuminate\View\View;
use Maatwebsite\Excel\Facades\Excel;

class SubscriberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(): View
    {
        return view('backend.blog.subscribers.index', [
            'subscribers' => Subscriber::latest()->paginate(25),
        ]);
    }

    public function export():
    ?\Symfony\Component\HttpFoundation\BinaryFileResponse
    {
        return Excel::download(new SubscribersExport(), 'subscribers' . date
            ('Y-m-d') . '.xlsx');
    }
}

resources/views/backend/teachers/create.blade.php
@extends('backend.layouts.app')
@section('pagetitle')
    <div class="page-title">
        <div class="title-env">
            <h1 class="title">Добавление учителя</h1>
            <p class="description">Добавление нового учителя</p>
        </div>
        <div class="breadcrumb-env">
            <ol class="breadcrumb bc-1">
                <li>
                    <a href="{{ url('backend/dashboard') }}"><i class="fa-home"></i>Главная</a>
                </li>
                <li>
                    <a href="{{ url('backend/teachers') }}">Учителя</a>
                </li>
                <li class="active">
                    <strong>Добавление учителя</strong>
                </li>
            </ol>
        </div>
    </div>
@endsection
@section('content')
    {{ Form::open(['url' => route('teachers.store'), 'method' => 'POST', 'class' => 'validate', "novalidate" => 'novalidate', 'files' => true]) }}
    <div class="panel panel-headerless">
        <div class="panel-body">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#main" data-toggle="tab">
                        <span class="visible-xs"><i class="fa-user"></i></span>
                        <span class="hidden-xs">Основная информация</span>
                    </a>
                </li>
                <li>
                    <a href="#text" data-toggle="tab">
                        <span class="visible-xs"><i class="fa-user"></i></span>
                        <span class="hidden-xs">Дополнительная информация</span>
                    </a>
                </li>
                <li>
                    <a href="#seo" data-toggle="tab">
                        <span class="visible-xs"><i class="fa-user"></i></span>
                        <span class="hidden-xs">SEO</span>
                    </a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="main">
                    <div class="member-form-add-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="col-md-10 col-sm-8">
                                    <div class="user-img">
                                        <a href="#">
                                            <img data-img="logo" src="{{ url('assets/images/user-4.png') }}"
                                                 class="img-circle js_image_link"
                                                 alt="user-pic"/>
                                        </a> logo
                                        <div>
                                            {{Form::file('logo', ['accept' => 'image/*', 'data-img' => 'logo'])}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="col-md-10 col-sm-8">
                                    <div class="user-img">
                                        <a href="#" class="js_form-link">
                                            <img id="photo_img" src="{{ url('assets/images/user-4.png') }}"
                                                 class="img-circle"
                                                 alt="user-pic"/>
                                        </a>
                                        <div>
                                            {{Form::file('thumbnail', ['accept' => 'image/*', 'id' => 'photo'])}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="member-form-inputs js_parent_div" data-csrf="{{ csrf_token() }}">
                        <div class="row form-group">
                            <div class="col-sm-3">
                                {{ Form::label('first_name', 'Фамилия *', ['class' => 'control-label']) }}
                            </div>
                            <div class="col-sm-9">
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <a href="#"><i class="fa-child"></i></a>
                                    </div>
                                    {{  Form::text('first_name', null, ['class' => 'form-control', 'data-validate' => 'required', 'data-message-required' => 'Поле обязательно для заполнения', "placeholder" => 'Фамилия'])}}
                                </div>
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-sm-3">
                                {{ Form::label('last_name', 'Имя *', ['class' => 'control-label']) }}
                            </div>
                            <div class="col-sm-9">
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <a href="#"><i class="fa-child"></i></a>
                                    </div>
                                    {{  Form::text('last_name', null, ['class' => 'form-control', 'data-validate' => 'required', 'data-message-required' => 'Поле обязательно для заполнения', "placeholder" => 'Имя'])}}
                                </div>
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-sm-3">
                                {{ Form::label('specialization', 'Специализация *', ['class' => 'control-label']) }}
                            </div>
                            <div class="col-sm-9">
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <a href="#"><i class="fa-check"></i></a>
                                    </div>
                                    {{  Form::text('specialization', null, ['class' => 'form-control', 'data-validate' => 'required', 'data-message-required' => 'Поле обязательно для заполнения', "placeholder" => 'Специализация'])}}
                                </div>
                            </div>
                        </div>
                        @if(count($courses) > 0)
                            <div class="row form-group">
                                <label class="col-sm-3 control-label" for="organization_id">Курсы</label>
                                <div class="col-sm-9">
                                    <select name="course_id[]" id="course_id" multiple class="form-control js_ch_multiple">
                                        @foreach($courses as $course)
                                            <option value="{{ $course->id }}">{{ $course->title }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        @endif
                        <div class="row form-group">
                            <div class="col-sm-3">
                                {{ Form::label('active', 'Активность', ['class' => 'control-label']) }}
                            </div>
                            <div class="col-sm-9">
                                {{ Form::checkbox('active', 1, 1, ['class' => 'iswitch iswitch-secondary']) }}
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-sm-3">
                                {{ Form::label('is_teacher', 'Учитель / Лектор', ['class' => 'control-label']) }}
                            </div>
                            <div class="col-sm-9">
                                {{ Form::checkbox('is_teacher', 1, 1, ['class' => 'iswitch iswitch-secondary']) }}
                            </div>
                        </div>
                        <div class="row form-group">
                            <label class="col-sm-2 control-label" for="js_clients_phones">Ссылка на профиль</label>
                            <div class="col-sm-10 js_parent">
                                <div class="input-group js_section">
                                    <div class="input-group-addon">
                                        <a href="#"><i class="fa-link"></i></a>
                                    </div>
                                    {{  Form::text('links[html_class][]', null, ['class' => 'form-control', "placeholder" => 'HTML class'])}}
                                    {{  Form::text('links[link][]', null, ['class' => 'form-control', "placeholder" => 'Ссылка на профиль'])}}
                                    <div class="input-group-addon js_remove_item">
                                        <a href="#">-</a>
                                    </div>
                                    <div class="input-group-addon js_add_item">
                                        <a href="#">+</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="text">
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="field-1">Краткое описание *</label>
                        <div class="col-sm-9">
                            {{  Form::textarea('introtext', null, ['class' => 'form-control ckeditor']) }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="field-1">Описание *</label>
                        <div class="col-sm-9">
                            {{  Form::textarea('description', null, ['class' => 'form-control ckeditor']) }}
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="seo">
                    <div class="row form-group">
                        <label class="col-sm-3" for="field-1">SEO-title</label>
                        <div class="col-sm-9">
                            {{  Form::text('seo_title', null, ['class' => 'form-control']) }}
                        </div>
                    </div>
                    <div class="row form-group">
                        <label class="col-sm-3" for="field-1">SEO-keywords</label>
                        <div class="col-sm-9">
                            {{  Form::text('seo_keywords', null, ['class' => 'form-control']) }}
                        </div>
                    </div>
                    <div class="row form-group">
                        <label class="col-sm-3 control-label" for="field-1">SEO-robots</label>
                        <div class="col-sm-9">
                            {{  Form::text('seo_robots', null, ['class' => 'form-control']) }}
                        </div>
                    </div>
                    <div class="row form-group">
                        <label class="col-sm-3 control-label" for="field-1">SEO-canonical</label>
                        <div class="col-sm-9">
                            {{  Form::text('seo_canonical', null, ['class' => 'form-control']) }}
                        </div>
                    </div>
                    <div class="row form-group">
                        <label class="col-sm-3 control-label" for="field-1">SEO-description</label>
                        <div class="col-sm-9">
                            {{  Form::textarea('seo_description', null, ['class' => 'form-control']) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <div class="form-group">
                <a href="{{ url('backend/teachers') }}" class="btn btn-white"><span class="fa-arrow-left"></span> Назад</a>
                <button type="submit" class="btn btn-success js_form_submit"><span class="fa-save"></span> <b>Сохранить</b>
                </button>
            </div>
        </div>
    </div>
    {{ Form::close() }}

@endsection

@section('styles')
    <link rel="stylesheet" href="{{ url('assets/js/select2/select2.css') }}">
    <link rel="stylesheet" href="{{ url('assets/js/select2/select2-bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url('assets/js/multiselect/css/multi-select.css') }}">
@endsection

@section('scripts')
    <script src="{{ url('assets/js/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ url('assets/js/datepicker/bootstrap-datepicker.js') }}"></script>
    <script src="{{ url('assets/js/select2/select2.min.js') }}"></script>
    <script src="{{ url('assets/js/multiselect/js/jquery.multi-select.js') }}"></script>
    <script src="{{ url('assets/js/jquery-validate/jquery.validate.min.js') }}"></script>
    <script src="{{ url('assets/js/inputmask/jquery.inputmask.bundle.js') }}"></script>

    {!! JsValidator::formRequest('App\Http\Requests\Teacher\TeacherRequest')->ignore('') !!}
@endsection