routes/backend.php
                    'Backend\Partner\PartnerController@sort');
                Route::resource('partners',
                    'Backend\Partner\PartnerController');
            });

            // applications
            Route::group(['middleware' => ['permission:applications']],
                function() {
                    // reviews
                    Route::resource('reviews',
                        'Backend\Review\ReviewController');

                    // applications(students)

                    Route::get('stapplications/export/',
                        'Backend\Application\StapplicationController@export')
                        ->name('stapplications.export');
                    Route::get('stapplications/update-all/',
                        'Backend\Application\StapplicationController@updateAll')
                        ->name('stapplications.update-all');
                    Route::resource('stapplications',
                        'Backend\Application\StapplicationController');

                    // applications(teachers)
                    Route::get('teachapplications/export/',
                        'Backend\Application\TeachapplicationController@export')
                        ->name('teachapplications.export');
                    Route::get('teachapplications/update-all/',
                        'Backend\Application\TeachapplicationController@updateAll')
                        ->name('teachapplications.update-all');
                    Route::resource('teachapplications',
                        'Backend\Application\TeachapplicationController');

                    // applications(callback)
                    Route::get('callbackapplications/update-all/',
                        'Backend\Application\CallbackapplicationController@updateAll')
                        ->name('callbackapplications.update-all');
                    Route::resource('callbackapplications',
                        'Backend\Application\CallbackapplicationController');

                    // applications(partners)
                    Route::get('partnerapplications/update-all/',
                        'Backend\Application\PartnerapplicationController@updateAll')
                        ->name('partnerapplications.update-all');
                    Route::resource('partnerapplications',
                        'Backend\Application\PartnerapplicationController');

                    // applications(events)
                    Route::get('eventapplications/export/',
                        'Backend\Application\EventapplicationController@export')
                        ->name('eventapplications.export');
                    Route::get('eventapplications/update-all/',
                        'Backend\Application\EventapplicationController@updateAll')
                        ->name('eventapplications.update-all');
                    Route::resource('eventapplications',
                        'Backend\Application\EventapplicationController');
                });

            // rewards
            Route::group(['middleware' => ['permission:rewards']], function() {

                Route::post('rewards/sort/',
                    'Backend\Reward\RewardController@sort');
                Route::resource('rewards', 'Backend\Reward\RewardController');
            });

            // blog
            Route::group(['prefix' => 'blog', 'as' => 'blog.'], function() {
                Route::resource('html-classes',
                    'Backend\Blog\HtmlClassController');
                Route::resource('tags', 'Backend\Blog\TagController');
                Route::resource('authors', 'Backend\Blog\AuthorController');
                Route::post('articles/sort',
                    'Backend\Blog\ArticleController@sort')
                    ->name('articles.sort');
                Route::resource('articles', 'Backend\Blog\ArticleController');
                Route::resource('blogs-content', 'Backend\Blog\BlogController')
                    ->except(['delete', 'show']);
                Route::group([
                    'prefix' => 'subscribers',
                    'as'     => 'subscribers.',
                ],
                    function() {
                        Route::get('/',
                            'Backend\Blog\SubscriberController@index')
                            ->name('index');
                        Route::get('/export',
                            'Backend\Blog\SubscriberController@export')
                            ->name('export');
                    });
            });

            // promocodes
            Route::group(['middleware' => ['permission:rewards']], function() {
                Route::resource('promocodes',
                    'Backend\Promocode\PromocodeController');
            });
            // hub
            Route::group(['middleware' => ['permission:hub']], function() {
                Route::get('hub-settings', 'Backend\Hub\HubController@index')
                    ->name('admin_hub');
                Route::get('hub-rooms', 'Backend\Hub\HubController@rooms')
                    ->name('hub_rooms');
                Route::get('hub-room-edit/{id}/edit',
                    'Backend\Hub\HubController@room_edit')
                    ->name('hub_room_edit');
                Route::get('hub-room-add/',
                    'Backend\Hub\HubController@add_room_index')
                    ->name('add_room_index');
                Route::get('hub-message/',
                    'Backend\Hub\HubMessageController@index')
                    ->name('hub_message');
                Route::get('hub-message/update-all/',
                    'Backend\Hub\HubMessageController@updateAll')
                    ->name('hub_message_show.update-all');
                Route::get('hub-message/{id}',
                    'Backend\Hub\HubMessageController@show')
                    ->name('hub_message_show');

            });
            Route::post('hub-settings-update',
                'Backend\Hub\HubController@update')->name('admin_hub_update');
            Route::post('hub-room-update/{id}',
                'Backend\Hub\HubController@room_update')
                ->name('admin_hub_room_update');
            Route::post('hub-room-create',
                'Backend\Hub\HubController@room_create')
                ->name('admin_hub_room_create');
            Route::post('hub-room-del/{id}',
                'Backend\Hub\HubController@room_del')
                ->name('admin_hub_room_del');

            // projectLife
            Route::group(['middleware' => ['permission:projectlife']],
                function() {
                    Route::get('project-life',
                        'Backend\ProjectLife\ProjectLifeController@index')
                        ->name('project_admin');
                    Route::post('projcet_life_update',
                        'Backend\ProjectLife\ProjectLifeController@update')
                        ->name('project_life_update');
                    Route::get('project-life-speakers',
                        'Backend\ProjectLife\ProcetLifeSpeakersController@index')
                        ->name('project_speakers');
                    Route::get('speaker/{id}/edit',
                        'Backend\ProjectLife\ProcetLifeSpeakersController@edit')
                        ->name('speaker_edit');
                    Route::post('projcet_speaker_update/{id}',
                        'Backend\ProjectLife\ProcetLifeSpeakersController@update')
                        ->name('project_speaker_update');
                    Route::get('projcet_speaker_add',
                        'Backend\ProjectLife\ProcetLifeSpeakersController@add')
                        ->name('project_speaker_add');
                    Route::post('projcet_speaker_creates',
                        'Backend\ProjectLife\ProcetLifeSpeakersController@create')
                        ->name('project_speaker_create');


                    Route::post('projcet_speaker_del/{id}',
                        'Backend\ProjectLife\ProcetLifeSpeakersController@del')
                        ->name('project_speaker_dell');
                    Route::get('project-programms',
                        'Backend\ProjectLife\ProjectProgrammController@index')
                        ->name('project_programms');
                    Route::get('project-programms/{id}/edit',
                        'Backend\ProjectLife\ProjectProgrammController@edit')
                        ->name('project_programms_edit');
                    Route::get('project-programms/add',
                        'Backend\ProjectLife\ProjectProgrammController@add')
                        ->name('project_programms_add');
                    Route::post('project-programms_update/{id}',
                        'Backend\ProjectLife\ProjectProgrammController@update')
                        ->name('project_programm_update');

                    Route::post('project-programms-del/{id}',
                        'Backend\ProjectLife\ProjectProgrammController@del')
                        ->name('project_programms_del');

                    Route::get('project-programms_timeline',
                        'Backend\ProjectLife\ProjectProgrammController@timeline')
                        ->name('project_timeline');
                    Route::post('projcet_speaker_create/',
                        'Backend\ProjectLife\ProjectProgrammController@create')
                        ->name('project_program_create');
                    Route::post('programms_timeline_update/',
                        'Backend\ProjectLife\ProjectProgrammController@timeline_update')
                        ->name('project_timeline_update');
                    Route::get('project_partners/',
                        'Backend\ProjectLife\ProcetLifePartnersController@index')
                        ->name('partners');
                    Route::get('project_partners_edit/{id}/edit',

routes/frontend.php
<?php
/**
 * Created by PhpStorm.
 * User: bredevil
 * Date: 11.03.2019
 * Time: 12:37
 */

Route::post('project_register/',
    'Frontend\ProjectLife\ProjectLifeController@register')
    ->name('project_register');

Route::get('/', 'Frontend\Home\HomeController@index')->name('home');
Route::post('teachers', 'Frontend\Home\HomeController@getTeachers')
    ->name('get-teachers');
Route::post('partners', 'Frontend\Home\HomeController@getPartners')
    ->name('get-partners');
Route::post('events', 'Frontend\Home\HomeController@getEvents')
    ->name('get-events');
Route::post('cities', 'Frontend\Home\HomeController@updateCity')
    ->name('update-city');

// life project 3.0
Route::get('/project-life', 'Frontend\ProjectLife\ProjectLifeController@index')
    ->name('project_home');


// course
Route::get('/course/{course_alias}', 'Frontend\Course\CourseController@index')
    ->name('course');

// tests
Route::group(['prefix' => 'tests', 'as' => 'tests.'], function() {
    Route::get('/result/', 'Frontend\Test\TestController@result')
        ->name('result');
    Route::any('/{id?}', 'Frontend\Test\TestController@index')
        ->name('question');
    Route::any('/check/{id?}', 'Frontend\Test\TestController@check')
        ->name('check');
});

// blog
Route::group(['prefix' => 'blog', 'as' => 'blog.'], function() {
    Route::get('/', 'Frontend\Blog\BlogController@index')
        ->name('blog');
    Route::get('/article/{alias}', 'Frontend\Blog\BlogController@inner')
        ->name('article');
    Route::post('/article/likes', 'Frontend\Blog\BlogController@likes')
        ->name('likes');
    Route::post('/subscribe', 'Frontend\Blog\BlogController@subscribe')
        ->name('subscribe');
    Route::post('/offer-article', 'Frontend\Blog\BlogController@offerArticle')
        ->name('offer-article');
});

// team
Route::get('team', 'Frontend\Creatorpage\CreatorpageController@index')
    ->name('team');
Route::post('get-team', 'Frontend\Creatorpage\CreatorpageController@getTeam')
    ->name('get-team');


//Хаб
Route::get('hub', 'Frontend\Hub\HubController@index')->name('hub');
Route::post('send_message', 'Frontend\Hub\HubController@message')
    ->name('send_message');

//
Route::get('hub', 'Frontend\Hub\HubController@index')->name('hub');

// event
Route::get('/event/{event_alias}', 'Frontend\Event\EventController@index')
    ->name('event');

// any page
Route::get('/{alias?}', 'Frontend\Redirect\RedirectController@index')
    ->where('alias', '([A-Za-z0-9\-_:/]+)')->name('page');

// forms
Route::post('add-feedback', 'Frontend\Form\FormController@addFeedback')
    ->name('add-feedback');
Route::post('add-partner', 'Frontend\Form\FormController@addPartner')
    ->name('add-partner');
Route::post('add-teacher', 'Frontend\Form\FormController@addTeacher')
    ->name('add-teacher');
Route::post('add-review', 'Frontend\Form\FormController@addReview')
    ->name('add-review');
Route::post('add-callback', 'Frontend\Form\FormController@addCallback')
    ->name('add-callback');
Route::post('add-event-application',
    'Frontend\Form\FormController@addEventApplication')
    ->name('add-event-application');

routes/web.php
<?php

    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    /**
     * frontend
     */
    Route::group(['middleware' => 'web'], function () {

        // admin panel
        include 'backend.php';
        // frontend
        include 'frontend.php';
    });

app/Http/Controllers/Backend/Blog/AuthorController.php
<?php

    namespace App\Http\Controllers\Backend\Blog;

    use App\Http\Requests\Blog\AuthorRequest;
    use App\Models\Blog\Author;
    use App\Repositories\Blog\AuthorRepository;
    use Illuminate\Http\Request;
    use App\Http\Controllers\Controller;
    use Illuminate\Support\Facades\File;
    use Illuminate\Support\Facades\Storage;

    class AuthorController extends Controller
    {
        /**
         * Display a listing of the resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function index()
        {
            return view('backend.blog.authors.index', [
                'authors' => Author::latest()->paginate(50),
            ]);
        }

        /**
         * Show the form for creating a new resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function create()
        {
            return view('backend.blog.authors.create', [
                'locales' => config('translatable.locales'),
            ]);
        }

        /**
         * Store a newly created resource in storage.
         *
         * @param  \Illuminate\Http\Request $request
         *
         * @return \Illuminate\Http\Response
         */
        public function store(AuthorRequest $request)
        {
            $author = Author::create($request->all());
            if ($request->thumbnail) {
                $author->thumbnail = md5($request->thumbnail->getClientOriginalName()) . '.' . $request->thumbnail->getClientOriginalExtension();
                Storage::disk('authors')
                    ->put($author->id . '/' . $author->thumbnail, File::get($request->thumbnail));
                $author->update();
            }
            return redirect(route('blog.authors.edit', $author->id))->with('success', 'Запись успешно создана');
        }

        /**
         * Display the specified resource.
         *
         * @param  int $id
         *
         * @return \Illuminate\Http\Response
         */
        public function show($id)
        {
            //
        }

        /**
         * Show the form for editing the specified resource.
         *
         * @param  int $id
         *
         * @return \Illuminate\Http\Response
         */
        public function edit($id)
        {
            return view('backend.blog.authors.edit', [
                'author'  => Author::findOrFail($id),
                'locales' => config('translatable.locales'),
            ]);
        }

        /**
         * Update the specified resource in storage.
         *
         * @param  \Illuminate\Http\Request $request
         * @param  int                      $id
         *
         * @return \Illuminate\Http\Response
         */
        public function update(AuthorRequest $request, $id)
        {
            $author = Author::findOrFail($id);
            if ($request->thumbnail) {
                File::cleanDirectory(storage_path('public/images/authors/' .
                $author->id . '/'));
                $author->thumbnail = md5($request->thumbnail->getClientOriginalName()) . '.' . $request->thumbnail->getClientOriginalExtension();
                Storage::disk('authors')
                    ->put($author->id . '/' . $author->thumbnail, File::get($request->thumbnail));
            }
            $author->update($request->all());
            return redirect(route('blog.authors.edit', $author->id))->with('success', 'Запись успешно обновлена');
        }

        /**
         * Remove the specified resource from storage.
         *
         * @param  int $id
         *
         * @return \Illuminate\Http\Response
         */
        public function destroy($id)
        {
            $author = Author::findOrFail($id);
            File::deleteDirectory(storage_path('public/images/authors/' . $author->id .
        '/'));
            $author->delete();
            return redirect(route('blog.authors.index'))->with('success', 'Запись успешно удалена');
        }
    }

resources/views/backend/blog/authors/create.blade.php
@extends('backend.layouts.app')
@section('pagetitle')
    <div class="page-title">
        <div class="title-env">
            <h1 class="title">Создание</h1>
        </div>
        <div class="breadcrumb-env">
            <ol class="breadcrumb bc-1">
                <li>
                    <a href="{{ route('dashboard') }}"><i class="fa-home"></i>Главная</a>
                </li>
                <li>
                    <a href="{{ route('blog.authors.index') }}">Authors</a>
                </li>
                <li class="active">
                    <strong>Создание </strong>
                </li>
            </ol>
        </div>
    </div>
@endsection
@section('content')

    {{ Form::open(['url' => route('blog.authors.store'), 'method' => 'POST', 'class' => 'validate form-horizontal js_form', "novalidate" => 'novalidate', 'autocomplete' => 'off', 'files' => true]) }}

    @include('backend.blog.authors.fields')

    {{ Form::close() }}

@endsection

resources/views/backend/blog/authors/edit.blade.php
@extends('backend.layouts.app')
@section('pagetitle')
    <div class="page-title">
        <div class="title-env">
            <h1 class="title">Редактирование</h1>
        </div>
        <div class="breadcrumb-env">
            <ol class="breadcrumb bc-1">
                <li>
                    <a href="{{ route('dashboard') }}"><i class="fa-home"></i>Главная</a>
                </li>
                <li>
                    <a href="{{ route('blog.authors.index') }}">Authors</a>
                </li>
                <li class="active">
                    <strong>Редактирование</strong>
                </li>
            </ol>
        </div>
    </div>
@endsection
@section('content')

    {{ Form::model($author, ['url' => route('blog.authors.update', ['author' => $author->id]), 'method' => 'PUT', 'class' => 'validate form-horizontal js_form', "novalidate" => 'novalidate', 'autocomplete' => 'off','files' => true]) }}

    @include('backend.blog.authors.fields')

    {{ Form::close() }}

    <div class="hidden">
        {!! Form::open(['route' => ['blog.authors.destroy', $author->id], 'method' => 'delete']) !!}
        {!! Form::submit('Удалить', ['class' => 'btn btn-danger js_destroy', 'onclick' => "return confirm('Вы уверены?')"]) !!}
        {!! Form::close() !!}
    </div>

@endsection

resources/views/backend/blog/authors/fields.blade.php
<div class="panel panel-headerless">
    <div class="panel-body">
        <ul class="nav nav-tabs">
            <li class="active">
                <a href="#main" data-toggle="tab">
                    <span class="visible-xs"><i class="fa-user"></i></span>
                    <span class="hidden-xs">Основная информация</span>
                </a>
            </li>
            <li>
                <a href="#locale" data-toggle="tab">
                    <span class="visible-xs"><i class="fa-user"></i></span>
                    <span class="hidden-xs">Контент</span>
                </a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="main">
                <div class="member-form-inputs js_parent_div" data-csrf="{{ csrf_token() }}">
                    <div class="row form-group">
                        <div class="user-img">
                            <a href="#">
                                <img data-img="thumbnail" src="{{ isset($author) ? $author->thumbnailMini : url('assets/images/user-4.png') }}"
                                     class="img-circle js_image_link"
                                     alt="user-pic"/>
                            </a> Основное изображение
                            <div class="invisible">
                                {{Form::file('thumbnail', ['accept' => 'image/*', 'data-img' => 'thumbnail'])}}
                            </div>
                        </div>
                    </div>
                    <div class="row form-group">
                        <label for="roleName">Email </label>
                        {!! Form::email('email', null, ['class'=>'form-control','placeholder'=>'Email','data-validation'=>'required', 'required']) !!}
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="locale">
                <div class="col-xs-3">
                    <ul class="nav nav-tabs tabs-left">
                        @foreach($locales as $lang)
                            <li class="@if ($loop->first) active @endif"><a data-toggle="tab"
                                                                            href="#v-pills-{{ $lang }}">{{ $lang }}
                                </a></li>
                        @endforeach
                    </ul>
                </div>
                <div class="col-xs-9">
                    <!-- Tab panes -->
                    <div class="tab-content">
                        @foreach($locales as $lang)
                            <div class="tab-pane  @if ($loop->first) active @endif" id="v-pills-{{ $lang }}">
                                <div class="form-group">
                                    <label for="roleName">Имя {{ $lang }}</label>
                                    {!! Form::textarea('' . $lang . '[first_name]', $author->{'first_name:'.$lang}??'',['class'=>'form-control','placeholder'=>'Имя '.$lang,'data-validation'=>'required', 'required']) !!}
                                </div>
                                <div class="form-group">
                                    <label for="roleName">Фамилия {{ $lang }}</label>
                                    {!! Form::textarea('' . $lang . '[last_name]', $author->{'last_name:'.$lang}??'',['class'=>'form-control','placeholder'=>'Фамилия '.$lang,'data-validation'=>'required', 'required']) !!}
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12">
        <div class="form-group">
            <a href="{{ route('blog.authors.index') }}" class="btn btn-white"><span class="fa-arrow-left"></span> Назад</a>
            <button type="submit" class="btn btn-success js_form_submit"><span class="fa-save"></span> <b>Сохранить</b>
            </button>
            @isset($author)
                <div class="pull-right">
                    <button class="btn btn-danger js_remove"><span class="fa-remove"></span> <b>Удалить</b>
                    </button>
                </div>
            @endisset
        </div>
    </div>
</div>

@section('scripts')
    <script src="{{ url('assets/js/select2/select2.min.js') }}"></script>
    <script src="{{ url('assets/js/jquery-validate/jquery.validate.min.js') }}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\Course\CourseRequest')->ignore('') !!}
@endsection

resources/views/backend/blog/authors/index.blade.php
@extends('backend.layouts.app')

@section('pagetitle')
    <div class="page-title">
        <div class="title-env">
            <h1 class="title">Authors</h1>
        </div>
        <div class="breadcrumb-env">
            <a href="{{ route('blog.authors.create') }}" class="btn btn-success"><span class="fa-plus"></span> Добавить</a>
        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <div class="tab-content">
                <div class="tab-pane active" id="all">

                    <table class="table table-hover members-table middle-align">
                        <thead>
                        <tr>
                            <th width="20%">ID</th>
                            <th width="30%">Thumbnail</th>
                            <th width="30%">Full name</th>
                            <th width="20%"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($authors as $author)
                            <tr>
                                <td class="hidden-xs hidden-sm">
                                    <span class="email">{!! $author->id !!}</span>
                                </td>
                                <td class="hidden-xs hidden-sm">
                                    <img src="{{ $author->thumbnailMini }}"/>
                                </td>
                                <td class="hidden-xs hidden-sm">
                                    <span class="email">{!! $author->fullName !!}</span>
                                </td>
                                <td>
                                    <a href="{!! route('blog.authors.edit', $author->id) !!}" class="btn btn-sm btn-success">
                                        <i class="linecons-pencil"></i>
                                    </a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6"><p class="text-center">По данному запросу результатов не найдено.</p></td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>

                    <div class="row">
                        <div class="col-sm-6">
                        </div>
                        <div class="col-sm-6 text-right text-center-sm">
                            {{ $authors->appends([request()])->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection